services:
  - type: web
    name: eventscout
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 120 app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
